language: objective-c
osx_image: xcode7.2
podfile: Example/Podfile
xcode_workspace: SlackReporter.scworkspace
xcode_sdk: iphonesimulator9.2
script:
- set -o pipefail && xctool test -workspace Example/SlackReporter.xcworkspace -scheme SlackReporter-Example -sdk iphonesimulator9.2 | xcpretty
- pod lib lint
