//
//  SlackReporterStyleKit.swift
//  SlackReporter
//
//  Created by Paul Lancefield on 24/12/2015.
//  Copyright (c) 2015 Paul Lancefield. All rights reserved.
//  Released under the MIT license
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class SlackReporterStyleKit : NSObject {

    //// Cache

    private struct Cache {
        static var imageOfSlackReporterButtonIcon: UIImage?
        static var slackReporterButtonIconTargets: [AnyObject]?
    }

    //// Drawing Methods

    public class func drawSlackReporterBarButtonIcon(frame frame: CGRect = CGRectMake(0, 0, 34, 34)) {

        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(frame.minX + 17.5, frame.minY + 22.5))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 17.5, frame.minY + 4))
        UIColor.blackColor().setFill()
        bezierPath.fill()
        UIColor.blackColor().setStroke()
        bezierPath.lineWidth = 1
        bezierPath.stroke()


        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(frame.minX + 11.5, frame.minY + 9.5))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 17.5, frame.minY + 3.5))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 23.5, frame.minY + 9.5))
        UIColor.blackColor().setStroke()
        bezier2Path.lineWidth = 1
        bezier2Path.stroke()


        //// Bezier 3 Drawing
        let bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPointMake(frame.minX + 3.5, frame.minY + 12.5))
        bezier3Path.addLineToPoint(CGPointMake(frame.minX + 3.5, frame.minY + 31.5))
        bezier3Path.addLineToPoint(CGPointMake(frame.minX + 31.5, frame.minY + 31.5))
        bezier3Path.addLineToPoint(CGPointMake(frame.minX + 31.5, frame.minY + 12.5))
        bezier3Path.addLineToPoint(CGPointMake(frame.minX + 22.17, frame.minY + 12.5))
        UIColor.blackColor().setStroke()
        bezier3Path.lineWidth = 1
        bezier3Path.stroke()


        //// Bezier 4 Drawing
        let bezier4Path = UIBezierPath()
        bezier4Path.moveToPoint(CGPointMake(frame.minX + 3.5, frame.minY + 12.5))
        bezier4Path.addLineToPoint(CGPointMake(frame.minX + 13, frame.minY + 12.5))
        UIColor.blackColor().setStroke()
        bezier4Path.lineWidth = 1
        bezier4Path.stroke()


        //// Text 3 Drawing
        let text3Path = UIBezierPath()
        text3Path.moveToPoint(CGPointMake(frame.minX + 6.38, frame.minY + 24.87))
        text3Path.addCurveToPoint(CGPointMake(frame.minX + 10.82, frame.minY + 28.28), controlPoint1: CGPointMake(frame.minX + 6.53, frame.minY + 26.94), controlPoint2: CGPointMake(frame.minX + 8.28, frame.minY + 28.28))
        text3Path.addCurveToPoint(CGPointMake(frame.minX + 15.3, frame.minY + 24.68), controlPoint1: CGPointMake(frame.minX + 13.56, frame.minY + 28.28), controlPoint2: CGPointMake(frame.minX + 15.3, frame.minY + 26.88))
        text3Path.addCurveToPoint(CGPointMake(frame.minX + 11.82, frame.minY + 21.33), controlPoint1: CGPointMake(frame.minX + 15.3, frame.minY + 22.92), controlPoint2: CGPointMake(frame.minX + 14.3, frame.minY + 21.96))
        text3Path.addLineToPoint(CGPointMake(frame.minX + 10.57, frame.minY + 21))
        text3Path.addCurveToPoint(CGPointMake(frame.minX + 8.26, frame.minY + 19.1), controlPoint1: CGPointMake(frame.minX + 8.92, frame.minY + 20.58), controlPoint2: CGPointMake(frame.minX + 8.26, frame.minY + 20.04))
        text3Path.addCurveToPoint(CGPointMake(frame.minX + 10.91, frame.minY + 17.09), controlPoint1: CGPointMake(frame.minX + 8.26, frame.minY + 17.89), controlPoint2: CGPointMake(frame.minX + 9.31, frame.minY + 17.09))
        text3Path.addCurveToPoint(CGPointMake(frame.minX + 13.62, frame.minY + 19.05), controlPoint1: CGPointMake(frame.minX + 12.4, frame.minY + 17.09), controlPoint2: CGPointMake(frame.minX + 13.41, frame.minY + 17.82))
        text3Path.addLineToPoint(CGPointMake(frame.minX + 15.12, frame.minY + 19.05))
        text3Path.addCurveToPoint(CGPointMake(frame.minX + 10.96, frame.minY + 15.74), controlPoint1: CGPointMake(frame.minX + 15, frame.minY + 17.12), controlPoint2: CGPointMake(frame.minX + 13.27, frame.minY + 15.74))
        text3Path.addCurveToPoint(CGPointMake(frame.minX + 6.72, frame.minY + 19.15), controlPoint1: CGPointMake(frame.minX + 8.43, frame.minY + 15.74), controlPoint2: CGPointMake(frame.minX + 6.72, frame.minY + 17.12))
        text3Path.addCurveToPoint(CGPointMake(frame.minX + 9.83, frame.minY + 22.38), controlPoint1: CGPointMake(frame.minX + 6.72, frame.minY + 20.85), controlPoint2: CGPointMake(frame.minX + 7.66, frame.minY + 21.83))
        text3Path.addLineToPoint(CGPointMake(frame.minX + 11.36, frame.minY + 22.78))
        text3Path.addCurveToPoint(CGPointMake(frame.minX + 13.76, frame.minY + 24.86), controlPoint1: CGPointMake(frame.minX + 13.02, frame.minY + 23.19), controlPoint2: CGPointMake(frame.minX + 13.76, frame.minY + 23.84))
        text3Path.addCurveToPoint(CGPointMake(frame.minX + 10.97, frame.minY + 26.92), controlPoint1: CGPointMake(frame.minX + 13.76, frame.minY + 26.05), controlPoint2: CGPointMake(frame.minX + 12.58, frame.minY + 26.92))
        text3Path.addCurveToPoint(CGPointMake(frame.minX + 7.89, frame.minY + 24.87), controlPoint1: CGPointMake(frame.minX + 9.26, frame.minY + 26.92), controlPoint2: CGPointMake(frame.minX + 8.07, frame.minY + 26.12))
        text3Path.addLineToPoint(CGPointMake(frame.minX + 6.38, frame.minY + 24.87))
        text3Path.closePath()
        text3Path.moveToPoint(CGPointMake(frame.minX + 21.88, frame.minY + 17.35))
        text3Path.addLineToPoint(CGPointMake(frame.minX + 24.76, frame.minY + 17.35))
        text3Path.addCurveToPoint(CGPointMake(frame.minX + 27.24, frame.minY + 19.64), controlPoint1: CGPointMake(frame.minX + 26.31, frame.minY + 17.35), controlPoint2: CGPointMake(frame.minX + 27.24, frame.minY + 18.21))
        text3Path.addCurveToPoint(CGPointMake(frame.minX + 24.83, frame.minY + 21.93), controlPoint1: CGPointMake(frame.minX + 27.24, frame.minY + 21.11), controlPoint2: CGPointMake(frame.minX + 26.37, frame.minY + 21.93))
        text3Path.addLineToPoint(CGPointMake(frame.minX + 21.88, frame.minY + 21.93))
        text3Path.addLineToPoint(CGPointMake(frame.minX + 21.88, frame.minY + 17.35))
        text3Path.closePath()
        text3Path.moveToPoint(CGPointMake(frame.minX + 21.88, frame.minY + 23.26))
        text3Path.addLineToPoint(CGPointMake(frame.minX + 24.83, frame.minY + 23.26))
        text3Path.addLineToPoint(CGPointMake(frame.minX + 27.4, frame.minY + 28))
        text3Path.addLineToPoint(CGPointMake(frame.minX + 29.15, frame.minY + 28))
        text3Path.addLineToPoint(CGPointMake(frame.minX + 26.38, frame.minY + 23.03))
        text3Path.addCurveToPoint(CGPointMake(frame.minX + 28.78, frame.minY + 19.59), controlPoint1: CGPointMake(frame.minX + 27.88, frame.minY + 22.55), controlPoint2: CGPointMake(frame.minX + 28.78, frame.minY + 21.26))
        text3Path.addCurveToPoint(CGPointMake(frame.minX + 24.96, frame.minY + 16.02), controlPoint1: CGPointMake(frame.minX + 28.78, frame.minY + 17.43), controlPoint2: CGPointMake(frame.minX + 27.27, frame.minY + 16.02))
        text3Path.addLineToPoint(CGPointMake(frame.minX + 20.39, frame.minY + 16.02))
        text3Path.addLineToPoint(CGPointMake(frame.minX + 20.39, frame.minY + 28))
        text3Path.addLineToPoint(CGPointMake(frame.minX + 21.88, frame.minY + 28))
        text3Path.addLineToPoint(CGPointMake(frame.minX + 21.88, frame.minY + 23.26))
        text3Path.closePath()
        UIColor.blackColor().setFill()
        text3Path.fill()
    }

    public class func drawSlackReporterButtonIcon() {

        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(21.5, 22.5))
        bezierPath.addLineToPoint(CGPointMake(21.5, 4))
        UIColor.blackColor().setFill()
        bezierPath.fill()
        UIColor.blackColor().setStroke()
        bezierPath.lineWidth = 1
        bezierPath.stroke()


        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(15.5, 9.5))
        bezier2Path.addLineToPoint(CGPointMake(21.5, 3.5))
        bezier2Path.addLineToPoint(CGPointMake(27.5, 9.5))
        UIColor.blackColor().setStroke()
        bezier2Path.lineWidth = 1
        bezier2Path.stroke()


        //// Bezier 3 Drawing
        let bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPointMake(3.5, 12.5))
        bezier3Path.addLineToPoint(CGPointMake(3.5, 37.5))
        bezier3Path.addLineToPoint(CGPointMake(39.5, 37.5))
        bezier3Path.addLineToPoint(CGPointMake(39.5, 12.5))
        bezier3Path.addLineToPoint(CGPointMake(26.36, 12.5))
        UIColor.blackColor().setStroke()
        bezier3Path.lineWidth = 1
        bezier3Path.stroke()


        //// Bezier 4 Drawing
        let bezier4Path = UIBezierPath()
        bezier4Path.moveToPoint(CGPointMake(3.5, 12.5))
        bezier4Path.addLineToPoint(CGPointMake(16, 12.5))
        UIColor.blackColor().setStroke()
        bezier4Path.lineWidth = 1
        bezier4Path.stroke()


        //// Text Drawing
        let textPath = UIBezierPath()
        textPath.moveToPoint(CGPointMake(16.4, 22.39))
        textPath.addLineToPoint(CGPointMake(18.29, 22.39))
        textPath.addCurveToPoint(CGPointMake(17.81, 20.26), controlPoint1: CGPointMake(18.26, 21.57), controlPoint2: CGPointMake(18.1, 20.86))
        textPath.addCurveToPoint(CGPointMake(16.64, 18.78), controlPoint1: CGPointMake(17.53, 19.67), controlPoint2: CGPointMake(17.13, 19.18))
        textPath.addCurveToPoint(CGPointMake(14.9, 17.92), controlPoint1: CGPointMake(16.14, 18.39), controlPoint2: CGPointMake(15.56, 18.1))
        textPath.addCurveToPoint(CGPointMake(12.76, 17.65), controlPoint1: CGPointMake(14.25, 17.74), controlPoint2: CGPointMake(13.53, 17.65))
        textPath.addCurveToPoint(CGPointMake(10.76, 17.91), controlPoint1: CGPointMake(12.08, 17.65), controlPoint2: CGPointMake(11.41, 17.74))
        textPath.addCurveToPoint(CGPointMake(9.01, 18.71), controlPoint1: CGPointMake(10.11, 18.09), controlPoint2: CGPointMake(9.53, 18.35))
        textPath.addCurveToPoint(CGPointMake(7.79, 20.07), controlPoint1: CGPointMake(8.5, 19.07), controlPoint2: CGPointMake(8.09, 19.52))
        textPath.addCurveToPoint(CGPointMake(7.32, 22.04), controlPoint1: CGPointMake(7.48, 20.63), controlPoint2: CGPointMake(7.32, 21.28))
        textPath.addCurveToPoint(CGPointMake(7.73, 23.75), controlPoint1: CGPointMake(7.32, 22.72), controlPoint2: CGPointMake(7.46, 23.29))
        textPath.addCurveToPoint(CGPointMake(8.82, 24.86), controlPoint1: CGPointMake(8.01, 24.2), controlPoint2: CGPointMake(8.37, 24.58))
        textPath.addCurveToPoint(CGPointMake(10.37, 25.56), controlPoint1: CGPointMake(9.28, 25.15), controlPoint2: CGPointMake(9.79, 25.38))
        textPath.addCurveToPoint(CGPointMake(12.12, 26.02), controlPoint1: CGPointMake(10.94, 25.73), controlPoint2: CGPointMake(11.53, 25.88))
        textPath.addCurveToPoint(CGPointMake(13.88, 26.41), controlPoint1: CGPointMake(12.72, 26.15), controlPoint2: CGPointMake(13.3, 26.28))
        textPath.addCurveToPoint(CGPointMake(15.42, 26.9), controlPoint1: CGPointMake(14.45, 26.53), controlPoint2: CGPointMake(14.96, 26.7))
        textPath.addCurveToPoint(CGPointMake(16.51, 27.69), controlPoint1: CGPointMake(15.87, 27.1), controlPoint2: CGPointMake(16.24, 27.36))
        textPath.addCurveToPoint(CGPointMake(16.92, 28.95), controlPoint1: CGPointMake(16.78, 28.01), controlPoint2: CGPointMake(16.92, 28.43))
        textPath.addCurveToPoint(CGPointMake(16.58, 30.29), controlPoint1: CGPointMake(16.92, 29.49), controlPoint2: CGPointMake(16.81, 29.94))
        textPath.addCurveToPoint(CGPointMake(15.7, 31.12), controlPoint1: CGPointMake(16.36, 30.64), controlPoint2: CGPointMake(16.07, 30.92))
        textPath.addCurveToPoint(CGPointMake(14.47, 31.55), controlPoint1: CGPointMake(15.34, 31.32), controlPoint2: CGPointMake(14.93, 31.47))
        textPath.addCurveToPoint(CGPointMake(13.12, 31.68), controlPoint1: CGPointMake(14.02, 31.64), controlPoint2: CGPointMake(13.57, 31.68))
        textPath.addCurveToPoint(CGPointMake(11.48, 31.47), controlPoint1: CGPointMake(12.56, 31.68), controlPoint2: CGPointMake(12.01, 31.61))
        textPath.addCurveToPoint(CGPointMake(10.08, 30.82), controlPoint1: CGPointMake(10.95, 31.33), controlPoint2: CGPointMake(10.48, 31.11))
        textPath.addCurveToPoint(CGPointMake(9.12, 29.69), controlPoint1: CGPointMake(9.69, 30.52), controlPoint2: CGPointMake(9.36, 30.15))
        textPath.addCurveToPoint(CGPointMake(8.75, 28.06), controlPoint1: CGPointMake(8.87, 29.24), controlPoint2: CGPointMake(8.75, 28.7))
        textPath.addLineToPoint(CGPointMake(6.86, 28.06))
        textPath.addCurveToPoint(CGPointMake(7.35, 30.43), controlPoint1: CGPointMake(6.86, 28.98), controlPoint2: CGPointMake(7.03, 29.76))
        textPath.addCurveToPoint(CGPointMake(8.7, 32.07), controlPoint1: CGPointMake(7.68, 31.09), controlPoint2: CGPointMake(8.13, 31.64))
        textPath.addCurveToPoint(CGPointMake(10.67, 33.02), controlPoint1: CGPointMake(9.27, 32.49), controlPoint2: CGPointMake(9.92, 32.81))
        textPath.addCurveToPoint(CGPointMake(13.06, 33.34), controlPoint1: CGPointMake(11.42, 33.23), controlPoint2: CGPointMake(12.22, 33.34))
        textPath.addCurveToPoint(CGPointMake(15.12, 33.09), controlPoint1: CGPointMake(13.74, 33.34), controlPoint2: CGPointMake(14.43, 33.26))
        textPath.addCurveToPoint(CGPointMake(17, 32.32), controlPoint1: CGPointMake(15.82, 32.93), controlPoint2: CGPointMake(16.44, 32.67))
        textPath.addCurveToPoint(CGPointMake(18.38, 30.93), controlPoint1: CGPointMake(17.56, 31.96), controlPoint2: CGPointMake(18.02, 31.5))
        textPath.addCurveToPoint(CGPointMake(18.92, 28.88), controlPoint1: CGPointMake(18.74, 30.36), controlPoint2: CGPointMake(18.92, 29.68))
        textPath.addCurveToPoint(CGPointMake(18.51, 27.04), controlPoint1: CGPointMake(18.92, 28.14), controlPoint2: CGPointMake(18.78, 27.53))
        textPath.addCurveToPoint(CGPointMake(17.41, 25.82), controlPoint1: CGPointMake(18.23, 26.55), controlPoint2: CGPointMake(17.87, 26.14))
        textPath.addCurveToPoint(CGPointMake(15.87, 25.05), controlPoint1: CGPointMake(16.96, 25.5), controlPoint2: CGPointMake(16.44, 25.24))
        textPath.addCurveToPoint(CGPointMake(14.12, 24.56), controlPoint1: CGPointMake(15.3, 24.86), controlPoint2: CGPointMake(14.71, 24.7))
        textPath.addCurveToPoint(CGPointMake(12.36, 24.17), controlPoint1: CGPointMake(13.52, 24.42), controlPoint2: CGPointMake(12.94, 24.29))
        textPath.addCurveToPoint(CGPointMake(10.82, 23.72), controlPoint1: CGPointMake(11.79, 24.05), controlPoint2: CGPointMake(11.28, 23.9))
        textPath.addCurveToPoint(CGPointMake(9.73, 23.01), controlPoint1: CGPointMake(10.36, 23.54), controlPoint2: CGPointMake(10, 23.3))
        textPath.addCurveToPoint(CGPointMake(9.32, 21.89), controlPoint1: CGPointMake(9.45, 22.73), controlPoint2: CGPointMake(9.32, 22.35))
        textPath.addCurveToPoint(CGPointMake(9.6, 20.66), controlPoint1: CGPointMake(9.32, 21.4), controlPoint2: CGPointMake(9.41, 20.99))
        textPath.addCurveToPoint(CGPointMake(10.36, 19.88), controlPoint1: CGPointMake(9.79, 20.33), controlPoint2: CGPointMake(10.04, 20.07))
        textPath.addCurveToPoint(CGPointMake(11.44, 19.45), controlPoint1: CGPointMake(10.67, 19.68), controlPoint2: CGPointMake(11.03, 19.54))
        textPath.addCurveToPoint(CGPointMake(12.68, 19.33), controlPoint1: CGPointMake(11.85, 19.37), controlPoint2: CGPointMake(12.26, 19.33))
        textPath.addCurveToPoint(CGPointMake(15.23, 20.05), controlPoint1: CGPointMake(13.71, 19.33), controlPoint2: CGPointMake(14.56, 19.57))
        textPath.addCurveToPoint(CGPointMake(16.4, 22.39), controlPoint1: CGPointMake(15.9, 20.54), controlPoint2: CGPointMake(16.28, 21.32))
        textPath.closePath()
        UIColor.blackColor().setFill()
        textPath.fill()


        //// Bezier 5 Drawing
        let bezier5Path = UIBezierPath()
        bezier5Path.moveToPoint(CGPointMake(32.12, 19.69))
        bezier5Path.addLineToPoint(CGPointMake(27.16, 19.69))
        bezier5Path.addLineToPoint(CGPointMake(27.16, 24.91))
        bezier5Path.addLineToPoint(CGPointMake(31.32, 24.91))
        bezier5Path.addCurveToPoint(CGPointMake(32.64, 24.81), controlPoint1: CGPointMake(31.78, 24.91), controlPoint2: CGPointMake(32.22, 24.88))
        bezier5Path.addCurveToPoint(CGPointMake(33.75, 24.4), controlPoint1: CGPointMake(33.06, 24.74), controlPoint2: CGPointMake(33.43, 24.6))
        bezier5Path.addCurveToPoint(CGPointMake(34.5, 23.58), controlPoint1: CGPointMake(34.06, 24.2), controlPoint2: CGPointMake(34.31, 23.92))
        bezier5Path.addCurveToPoint(CGPointMake(34.79, 22.25), controlPoint1: CGPointMake(34.69, 23.24), controlPoint2: CGPointMake(34.79, 22.79))
        bezier5Path.addCurveToPoint(CGPointMake(34.16, 20.4), controlPoint1: CGPointMake(34.79, 21.49), controlPoint2: CGPointMake(34.58, 20.88))
        bezier5Path.addCurveToPoint(CGPointMake(32.12, 19.69), controlPoint1: CGPointMake(33.74, 19.92), controlPoint2: CGPointMake(33.06, 19.69))
        bezier5Path.closePath()
        bezier5Path.moveToPoint(CGPointMake(35.57, 19.06))
        bezier5Path.addCurveToPoint(CGPointMake(36.78, 21.93), controlPoint1: CGPointMake(36.38, 19.76), controlPoint2: CGPointMake(36.78, 20.71))
        bezier5Path.addCurveToPoint(CGPointMake(36.16, 24.33), controlPoint1: CGPointMake(36.78, 22.84), controlPoint2: CGPointMake(36.58, 23.64))
        bezier5Path.addCurveToPoint(CGPointMake(34.18, 25.73), controlPoint1: CGPointMake(35.75, 25.01), controlPoint2: CGPointMake(35.09, 25.48))
        bezier5Path.addCurveToPoint(CGPointMake(35.24, 26.2), controlPoint1: CGPointMake(34.61, 25.86), controlPoint2: CGPointMake(34.96, 26))
        bezier5Path.addCurveToPoint(CGPointMake(35.89, 26.9), controlPoint1: CGPointMake(35.51, 26.39), controlPoint2: CGPointMake(35.73, 26.63))
        bezier5Path.addCurveToPoint(CGPointMake(36.25, 27.81), controlPoint1: CGPointMake(36.05, 27.17), controlPoint2: CGPointMake(36.17, 27.48))
        bezier5Path.addCurveToPoint(CGPointMake(36.42, 28.86), controlPoint1: CGPointMake(36.32, 28.15), controlPoint2: CGPointMake(36.38, 28.5))
        bezier5Path.addCurveToPoint(CGPointMake(36.49, 29.98), controlPoint1: CGPointMake(36.45, 29.23), controlPoint2: CGPointMake(36.47, 29.6))
        bezier5Path.addCurveToPoint(CGPointMake(36.59, 31.09), controlPoint1: CGPointMake(36.5, 30.35), controlPoint2: CGPointMake(36.54, 30.72))
        bezier5Path.addCurveToPoint(CGPointMake(36.83, 32.13), controlPoint1: CGPointMake(36.65, 31.45), controlPoint2: CGPointMake(36.73, 31.8))
        bezier5Path.addCurveToPoint(CGPointMake(37.31, 33), controlPoint1: CGPointMake(36.94, 32.46), controlPoint2: CGPointMake(37.1, 32.75))
        bezier5Path.addLineToPoint(CGPointMake(35.08, 33))
        bezier5Path.addCurveToPoint(CGPointMake(34.8, 32.37), controlPoint1: CGPointMake(34.94, 32.85), controlPoint2: CGPointMake(34.85, 32.64))
        bezier5Path.addCurveToPoint(CGPointMake(34.7, 31.48), controlPoint1: CGPointMake(34.75, 32.1), controlPoint2: CGPointMake(34.72, 31.81))
        bezier5Path.addCurveToPoint(CGPointMake(34.66, 30.42), controlPoint1: CGPointMake(34.69, 31.15), controlPoint2: CGPointMake(34.67, 30.8))
        bezier5Path.addCurveToPoint(CGPointMake(34.53, 29.3), controlPoint1: CGPointMake(34.65, 30.04), controlPoint2: CGPointMake(34.6, 29.67))
        bezier5Path.addCurveToPoint(CGPointMake(34.32, 28.26), controlPoint1: CGPointMake(34.48, 28.94), controlPoint2: CGPointMake(34.41, 28.59))
        bezier5Path.addCurveToPoint(CGPointMake(33.93, 27.4), controlPoint1: CGPointMake(34.24, 27.94), controlPoint2: CGPointMake(34.11, 27.65))
        bezier5Path.addCurveToPoint(CGPointMake(33.21, 26.82), controlPoint1: CGPointMake(33.74, 27.16), controlPoint2: CGPointMake(33.51, 26.96))
        bezier5Path.addCurveToPoint(CGPointMake(32.04, 26.59), controlPoint1: CGPointMake(32.92, 26.67), controlPoint2: CGPointMake(32.53, 26.59))
        bezier5Path.addLineToPoint(CGPointMake(27.16, 26.59))
        bezier5Path.addLineToPoint(CGPointMake(27.16, 33))
        bezier5Path.addLineToPoint(CGPointMake(25.17, 33))
        bezier5Path.addLineToPoint(CGPointMake(25.17, 18.01))
        bezier5Path.addLineToPoint(CGPointMake(32.22, 18.01))
        bezier5Path.addCurveToPoint(CGPointMake(35.57, 19.06), controlPoint1: CGPointMake(33.65, 18.01), controlPoint2: CGPointMake(34.77, 18.36))
        bezier5Path.closePath()
        UIColor.blackColor().setFill()
        bezier5Path.fill()
    }

    //// Generated Images

    public class func imageOfSlackReporterBarButtonIcon(frame frame: CGRect = CGRectMake(0, 0, 34, 34)) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, 0)
            SlackReporterStyleKit.drawSlackReporterBarButtonIcon(frame: CGRectMake(0, 0, frame.size.width, frame.size.height))

        let imageOfSlackReporterBarButtonIcon = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return imageOfSlackReporterBarButtonIcon
    }

    public class var imageOfSlackReporterButtonIcon: UIImage {
        if Cache.imageOfSlackReporterButtonIcon != nil {
            return Cache.imageOfSlackReporterButtonIcon!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(44, 44), false, 0)
            SlackReporterStyleKit.drawSlackReporterButtonIcon()

        Cache.imageOfSlackReporterButtonIcon = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfSlackReporterButtonIcon!
    }

    //// Customization Infrastructure

    @IBOutlet var slackReporterButtonIconTargets: [AnyObject]! {
        get { return Cache.slackReporterButtonIconTargets }
        set {
            Cache.slackReporterButtonIconTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector("setImage:", withObject: SlackReporterStyleKit.imageOfSlackReporterButtonIcon)
            }
        }
    }

}
